apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-service
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-service
  template:
    metadata:
      labels:
        app: dummy-service
    spec:
      containers:
      - name: dummy-service
        image: hashicorp/http-echo:latest
        args:
        - "-text=Hello from dummy-service"
        ports:
        - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: dummy-service
  namespace: apps
spec:
  selector:
    app: dummy-service
  ports:
  - port: 80
    targetPort: 5678
