apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-logger
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-logger
  template:
    metadata:
      labels:
        app: webhook-logger
    spec:
      containers:
      - name: webhook-logger
        image: mendhak/http-https-echo:33
        ports:
        - containerPort: 8080
        env:
        - name: HTTP_PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-logger
  namespace: apps
spec:
  selector:
    app: webhook-logger
  ports:
  - port: 80
    targetPort: 8080
